spring:
  profiles:
    active: testnet
  datasource:
    url: jdbc:postgresql://localhost:5432/trading?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: INFO
    com.tradingbot: DEBUG

telegram:
  bot:
    username: v1TGBot
    token: 8064498072:AAGGn9DVOMKq0jEAUurYS5ZQ1FHtTpkkI_I
    admin-id: 403753468
