package com.tradingbot.infrastructure.persistence.entity;

import com.tradingbot.common.enums.OrderSide;
import com.tradingbot.domain.model.OrderEntity;
import com.tradingbot.domain.model.User;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * IDENTITY ENTITY — Исполнение ордера на бирже (Trade).
 *
 * Является частью жизненного цикла OrderEntity.
 * Append-only после создания — никогда не обновляется бизнес-логикой.
 *
 * Изменения относительно v1:
 * - orderId: String → ManyToOne FK → orders.id (устранена "висячая" строковая ссылка)
 * - userId: добавлен ManyToOne FK — изоляция данных между пользователями
 * - clientOrderId: сохранён как денормализованное поле для быстрого lookup без JOIN
 * - sequenceId: убран @Column(insertable=false) без источника → GENERATED BY DEFAULT (DDL-side)
 * - externalTradeId: удалён как дубль exchangeTradeId
 */
@Entity
@Table(
        name = "trades",
        indexes = {
                @Index(name = "idx_trades_order_id",        columnList = "order_id"),
                @Index(name = "idx_trades_client_order_id", columnList = "client_order_id"),
                @Index(name = "idx_trades_symbol_executed", columnList = "symbol, executed_at"),
                @Index(name = "idx_trades_user_strategy",   columnList = "user_id, strategy_id, executed_at")
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TradeEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ── Order relation ────────────────────────────────────────────────────────

    /**
     * Ордер-родитель.
     * LAZY — критично: trade-листы грузятся пачками, eager = катастрофа.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "order_id", nullable = false, foreignKey = @ForeignKey(name = "fk_trades_order"))
    private OrderEntity order;

    /** Денормализованный FK для запросов без join. */
    @Column(name = "order_id", insertable = false, updatable = false, nullable = false)
    private Long orderId;

    /**
     * Денормализованный clientOrderId — для outbox reconciliation и exchange lookup
     * без дополнительного JOIN на orders.
     */
    @Column(name = "client_order_id", nullable = false, length = 128)
    private String clientOrderId;

    // ── User relation ─────────────────────────────────────────────────────────

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false, foreignKey = @ForeignKey(name = "fk_trades_user"))
    private User user;

    @Column(name = "user_id", insertable = false, updatable = false, nullable = false)
    private Long userId;

    // ── Instrument ────────────────────────────────────────────────────────────

    @Column(name = "symbol", nullable = false, length = 32)
    private String symbol;

    @Enumerated(EnumType.STRING)
    @Column(name = "side", nullable = false, length = 8)
    private OrderSide side;

    @Column(name = "strategy_id", nullable = false, length = 128)
    private String strategyId;

    // ── Execution details ─────────────────────────────────────────────────────

    @Column(name = "quantity", nullable = false, precision = 28, scale = 8)
    private BigDecimal quantity;

    @Column(name = "price", nullable = false, precision = 28, scale = 8)
    private BigDecimal price;

    @Column(name = "net_quantity", precision = 28, scale = 8)
    private BigDecimal netQuantity;

    @Column(name = "avg_entry_price", precision = 28, scale = 8)
    private BigDecimal avgEntryPrice;

    // ── P&L ──────────────────────────────────────────────────────────────────

    @Column(name = "realized_pnl", precision = 28, scale = 8)
    private BigDecimal realizedPnl;

    @Column(name = "commission", precision = 28, scale = 8)
    private BigDecimal commission;

    @Column(name = "commission_asset", length = 16)
    private String commissionAsset;

    // ── External references ───────────────────────────────────────────────────

    /**
     * ID трейда на бирже. UNIQUE — гарантирует идемпотентность при повторных
     * уведомлениях от биржи (at-least-once delivery).
     */
    @Column(name = "exchange_trade_id", unique = true, length = 128)
    private String exchangeTradeId;

    // externalTradeId УДАЛЁН — дубль exchangeTradeId

    // ── Sequence ──────────────────────────────────────────────────────────────

    /**
     * Монотонный sequence для упорядоченного replay.
     * GENERATED ALWAYS AS IDENTITY на стороне БД — не трогаем из приложения.
     */
    @Column(name = "sequence_id", insertable = false, updatable = false)
    private Long sequenceId;

    // ── Timestamps ────────────────────────────────────────────────────────────

    @Column(name = "executed_at")
    private Instant executedAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @PrePersist
    protected void onCreate() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }
}