CREATE TABLE orders (
    id VARCHAR(255) PRIMARY KEY,
    symbol VARCHAR(255) NOT NULL,
    side VARCHAR(255) NOT NULL,
    quantity NUMERIC(38, 8) NOT NULL,
    price NUMERIC(38, 8) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE positions (
    symbol VARCHAR(255) PRIMARY KEY,
    quantity NUMERIC(38, 8) NOT NULL,
    entry_price NUMERIC(38, 8) NOT NULL
);

CREATE TABLE trades (
    id VARCHAR(255) PRIMARY KEY,
    order_id VARCHAR(255) NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    side VARCHAR(255) NOT NULL,
    quantity NUMERIC(38, 8) NOT NULL,
    price NUMERIC(38, 8) NOT NULL,
    executed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
