-- =============================================================================
-- V1__init.sql — TradingBot Schema (Flyway)
-- ВАЖНО: ЗАМЕНЯЕТ V1__Initial_DDD_Schema.sql
-- Действие: удалить старый файл, положить этот под тем же именем папки
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "btree_gin";

-- =============================================================================
-- РЕШЕНИЕ ПО ENUM: VARCHAR + CHECK вместо CREATE TYPE ... AS ENUM
-- Причина: Hibernate @Enumerated(EnumType.STRING) пишет чистую строку.
-- PostgreSQL ENUM требовал бы кастомный UserType или @Type аннотацию.
-- VARCHAR + CHECK: работает с Hibernate из коробки, легко расширяется.
-- =============================================================================

-- =============================================================================
-- users
-- Entity: com.tradingbot.domain.model.User
-- =============================================================================
CREATE TABLE users (
                       id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       chat_id     BIGINT       NOT NULL,
                       username    VARCHAR(255),
                       tier        VARCHAR(16)  NOT NULL DEFAULT 'FREE'
                           CONSTRAINT chk_users_tier CHECK (tier IN ('FREE','PRO','VIP')),
                       active      BOOLEAN      NOT NULL DEFAULT TRUE,
                       created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
                       updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
                       CONSTRAINT uq_users_chat_id UNIQUE (chat_id)
);

CREATE INDEX idx_users_active ON users (active) WHERE active = TRUE;


-- =============================================================================
-- orders
-- Entity: com.tradingbot.domain.model.OrderEntity
-- =============================================================================
CREATE TABLE orders (
                        id                   BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        client_order_id      VARCHAR(128)   NOT NULL,
                        exchange_order_id    VARCHAR(128),
                        user_id              BIGINT         NOT NULL,
                        strategy_id          VARCHAR(128)   NOT NULL,
                        symbol               VARCHAR(32)    NOT NULL,
                        side                 VARCHAR(8)     NOT NULL
                            CONSTRAINT chk_orders_side CHECK (side IN ('BUY','SELL')),
                        type                 VARCHAR(16)    NOT NULL
                            CONSTRAINT chk_orders_type CHECK (type IN ('MARKET','LIMIT','STOP_LOSS','TAKE_PROFIT')),
                        quantity             NUMERIC(28,8)  NOT NULL,
                        price                NUMERIC(28,8)  NOT NULL,
                        stop_loss            NUMERIC(28,8),
                        take_profit          NUMERIC(28,8),
                        status               VARCHAR(32)    NOT NULL DEFAULT 'NEW'
                            CONSTRAINT chk_orders_status CHECK (
                                status IN ('NEW','ACCEPTED','APPROVED','PENDING_EXECUTION',
                                           'EXECUTING','FILLED','REJECTED','ERROR')),
                        execution_owner      VARCHAR(255),
                        execution_expires_at TIMESTAMPTZ,
                        version              BIGINT         NOT NULL DEFAULT 0,
                        risk_state_version   BIGINT         NOT NULL DEFAULT 0,
                        created_at           TIMESTAMPTZ    NOT NULL DEFAULT now(),
                        updated_at           TIMESTAMPTZ    NOT NULL DEFAULT now(),
                        CONSTRAINT fk_orders_user        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
                        CONSTRAINT uq_orders_client_order_id UNIQUE (client_order_id)
);

CREATE INDEX idx_orders_status          ON orders (status);
CREATE INDEX idx_orders_user_id         ON orders (user_id);
CREATE INDEX idx_orders_strategy_status ON orders (strategy_id, status);
CREATE INDEX idx_orders_executing_lock  ON orders (execution_owner, execution_expires_at)
    WHERE status = 'EXECUTING';
CREATE INDEX idx_orders_exchange_id     ON orders (exchange_order_id)
    WHERE exchange_order_id IS NOT NULL;


-- =============================================================================
-- trades
-- Entity: com.tradingbot.infrastructure.persistence.entity.TradeEntity
-- =============================================================================
CREATE TABLE trades (
                        id                BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id          BIGINT         NOT NULL,
                        client_order_id   VARCHAR(128)   NOT NULL,
                        user_id           BIGINT         NOT NULL,
                        strategy_id       VARCHAR(128)   NOT NULL,
                        symbol            VARCHAR(32)    NOT NULL,
                        side              VARCHAR(8)     NOT NULL
                            CONSTRAINT chk_trades_side CHECK (side IN ('BUY','SELL')),
                        quantity          NUMERIC(28,8)  NOT NULL,
                        price             NUMERIC(28,8)  NOT NULL,
                        net_quantity      NUMERIC(28,8),
                        avg_entry_price   NUMERIC(28,8),
                        realized_pnl      NUMERIC(28,8),
                        commission        NUMERIC(28,8),
                        commission_asset  VARCHAR(16),
                        exchange_trade_id VARCHAR(128),
    -- GENERATED ALWAYS AS IDENTITY: Hibernate не пишет это поле (insertable=false)
                        sequence_id       BIGINT         GENERATED ALWAYS AS IDENTITY,
                        executed_at       TIMESTAMPTZ,
                        created_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
                        CONSTRAINT fk_trades_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT,
                        CONSTRAINT fk_trades_user  FOREIGN KEY (user_id)  REFERENCES users (id)  ON DELETE RESTRICT,
                        CONSTRAINT uq_trades_exchange_trade_id UNIQUE (exchange_trade_id)
);

CREATE INDEX idx_trades_order_id        ON trades (order_id);
CREATE INDEX idx_trades_client_order_id ON trades (client_order_id);
CREATE INDEX idx_trades_symbol_executed ON trades (symbol, executed_at DESC);
CREATE INDEX idx_trades_user_strategy   ON trades (user_id, strategy_id, executed_at DESC);


-- =============================================================================
-- positions
-- Entity: com.tradingbot.domain.model.PositionEntity
-- ВАЖНО: Entity поле quantity → колонка net_quantity
--        Entity поле entryPrice → колонка avg_entry_price
-- =============================================================================
CREATE TABLE positions (
                           id               BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           symbol           VARCHAR(32)    NOT NULL,
                           strategy_id      VARCHAR(128)   NOT NULL,
                           user_id          BIGINT         NOT NULL,
                           net_quantity     NUMERIC(28,8)  NOT NULL DEFAULT 0,
                           avg_entry_price  NUMERIC(28,8),
                           realized_pnl     NUMERIC(28,8)  NOT NULL DEFAULT 0,
                           stop_loss        NUMERIC(28,8),
                           take_profit      NUMERIC(28,8),
                           status           VARCHAR(16)    NOT NULL DEFAULT 'OPEN'
                               CONSTRAINT chk_positions_status CHECK (status IN ('OPEN','CLOSING','CLOSED')),
                           last_trade_id    BIGINT,
                           close_request_id UUID,
                           version          BIGINT         NOT NULL DEFAULT 0,
                           created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
                           updated_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
                           CONSTRAINT fk_positions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
                           CONSTRAINT uq_positions_open UNIQUE (symbol, strategy_id, user_id)
);

CREATE INDEX idx_positions_user_strategy ON positions (user_id, strategy_id);
CREATE INDEX idx_positions_symbol_status ON positions (symbol, status);
CREATE INDEX idx_positions_close_req     ON positions (close_request_id)
    WHERE close_request_id IS NOT NULL;


-- =============================================================================
-- signals
-- Entity: com.tradingbot.domain.event.SignalEntity
-- =============================================================================
CREATE TABLE signals (
                         id           BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         symbol       VARCHAR(32)    NOT NULL,
                         type         VARCHAR(8)     NOT NULL
                             CONSTRAINT chk_signals_type CHECK (type IN ('BUY','SELL','HOLD')),
                         strategy_id  VARCHAR(128)   NOT NULL,
                         user_id      BIGINT,
                         price        NUMERIC(28,8),
                         take_profit1 NUMERIC(28,8),
                         take_profit2 NUMERIC(28,8),
                         stop_loss    NUMERIC(28,8),
                         created_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
                         timestamp    TIMESTAMPTZ,
                         CONSTRAINT fk_signals_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_signals_strategy_created ON signals (strategy_id, created_at DESC);
CREATE INDEX idx_signals_symbol_created   ON signals (symbol, created_at DESC);


-- =============================================================================
-- outbox_events
-- Entity: com.tradingbot.infrastructure.persistence.entity.OutboxEventEntity
-- =============================================================================
CREATE TABLE outbox_events (
                               event_id        UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
                               client_order_id VARCHAR(128)   NOT NULL,
                               type            VARCHAR(128)   NOT NULL,
                               payload         JSONB          NOT NULL,
                               status          VARCHAR(16)    NOT NULL DEFAULT 'PENDING'
                                   CONSTRAINT chk_outbox_status CHECK (status IN ('PENDING','SENT','FAILED')),
                               retry_count     INT            NOT NULL DEFAULT 0,
                               max_retries     INT            NOT NULL DEFAULT 5,
                               error_message   TEXT,
                               created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
                               processed_at    TIMESTAMPTZ,
                               next_retry_at   TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE INDEX idx_outbox_pending         ON outbox_events (next_retry_at) WHERE status = 'PENDING';
CREATE INDEX idx_outbox_client_order_id ON outbox_events (client_order_id);
CREATE INDEX idx_outbox_failed          ON outbox_events (created_at)    WHERE status = 'FAILED';


-- =============================================================================
-- execution_idempotency
-- Entity: com.tradingbot.infrastructure.persistence.entity.ExecutionIdempotencyEntity
-- NOTE: добавлена колонка order_id (nullable) — используется в native query
--       ExecutionIdempotencyRepository.tryInsertIdempotency()
-- =============================================================================
CREATE TABLE execution_idempotency (
                                       client_order_id   VARCHAR(128)  PRIMARY KEY,
                                       exchange_order_id VARCHAR(128),
                                       order_id          VARCHAR(128),   -- legacy native query field
                                       status            VARCHAR(16)   NOT NULL
                                           CONSTRAINT chk_exec_idemp_status
                                               CHECK (status IN ('IN_PROGRESS','SUCCESS','FAILED')),
                                       error_message     TEXT,
                                       created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
                                       updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_exec_idemp_exchange_id ON execution_idempotency (exchange_order_id)
    WHERE exchange_order_id IS NOT NULL;


-- =============================================================================
-- risk_events
-- Entity: com.tradingbot.domain.event.RiskEventEntity
-- =============================================================================
CREATE TABLE risk_events (
                             id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             event_id     UUID         NOT NULL DEFAULT gen_random_uuid(),
                             aggregate_id BIGINT       NOT NULL,
                             version      BIGINT       NOT NULL,
                             event_type   VARCHAR(128) NOT NULL,
                             payload      JSONB        NOT NULL,
                             created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
                             CONSTRAINT uq_risk_events_event_id          UNIQUE (event_id),
                             CONSTRAINT uq_risk_events_aggregate_version UNIQUE (aggregate_id, version)
);

CREATE INDEX idx_risk_events_aggregate ON risk_events (aggregate_id, version);
CREATE INDEX idx_risk_events_type      ON risk_events (event_type, created_at DESC);
CREATE INDEX idx_risk_events_payload   ON risk_events USING GIN (payload);


-- =============================================================================
-- risk_snapshots
-- Entity: com.tradingbot.infrastructure.persistence.entity.RiskSnapshotEntity
-- NOTE: aggregate_id добавлен для обратной совместимости с
--       RiskSnapshotRepository.findFirstByAggregateIdOrderByLastVersionDesc()
-- =============================================================================
CREATE TABLE risk_snapshots (
                                id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                snapshot_id  VARCHAR(128)  NOT NULL,
                                aggregate_id VARCHAR(128),
                                version      BIGINT        NOT NULL DEFAULT 0,
                                state_json   JSONB         NOT NULL,
                                timestamp    TIMESTAMPTZ   NOT NULL DEFAULT now(),
                                CONSTRAINT uq_risk_snapshots_snapshot_id UNIQUE (snapshot_id)
);

CREATE INDEX idx_risk_snapshots_timestamp    ON risk_snapshots (timestamp DESC);
CREATE INDEX idx_risk_snapshots_aggregate_id ON risk_snapshots (aggregate_id)
    WHERE aggregate_id IS NOT NULL;


-- =============================================================================
-- risk_state_snapshots
-- Entity: com.tradingbot.infrastructure.persistence.entity.RiskStateSnapshotEntity
-- =============================================================================
CREATE TABLE risk_state_snapshots (
                                      id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      timestamp           TIMESTAMPTZ   NOT NULL DEFAULT now(),
                                      balance             NUMERIC(28,8) NOT NULL,
                                      equity              NUMERIC(28,8) NOT NULL,
                                      daily_pnl           NUMERIC(28,8) NOT NULL,
                                      max_equity          NUMERIC(28,8) NOT NULL,
                                      processed_event_ids JSONB         NOT NULL DEFAULT '[]'::jsonb,
                                      strategy_id         VARCHAR(128),
                                      user_id             BIGINT,
                                      CONSTRAINT fk_risk_state_snap_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_risk_state_snap_timestamp ON risk_state_snapshots (timestamp DESC);
CREATE INDEX idx_risk_state_snap_strategy  ON risk_state_snapshots (strategy_id, timestamp DESC)
    WHERE strategy_id IS NOT NULL;


-- =============================================================================
-- equity_snapshots
-- Entity: com.tradingbot.infrastructure.persistence.entity.EquitySnapshotEntity
-- =============================================================================
CREATE TABLE equity_snapshots (
                                  id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  timestamp      TIMESTAMPTZ   NOT NULL,
                                  balance        NUMERIC(28,8) NOT NULL,
                                  equity         NUMERIC(28,8) NOT NULL,
                                  unrealized_pnl NUMERIC(28,8) NOT NULL,
                                  strategy_id    VARCHAR(128)  NOT NULL,
                                  user_id        BIGINT,
                                  CONSTRAINT fk_equity_snap_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_equity_snap_strategy_time ON equity_snapshots (strategy_id, timestamp DESC);
CREATE INDEX idx_equity_snap_user_time     ON equity_snapshots (user_id, timestamp DESC)
    WHERE user_id IS NOT NULL;


-- =============================================================================
-- TRIGGERS: auto-update updated_at
-- =============================================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_positions_updated_at
    BEFORE UPDATE ON positions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_exec_idemp_updated_at
    BEFORE UPDATE ON execution_idempotency FOR EACH ROW EXECUTE FUNCTION set_updated_at();